# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ryuzakii/igvc/my-repos/blu-chan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ryuzakii/igvc/my-repos/blu-chan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryuzakii/igvc/my-repos/blu-chan/CMakeFiles /home/ryuzakii/igvc/my-repos/blu-chan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ryuzakii/igvc/my-repos/blu-chan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named red

# Build rule for target.
red: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 red
.PHONY : red

# fast build rule for target.
red/fast:
	$(MAKE) -f CMakeFiles/red.dir/build.make CMakeFiles/red.dir/build
.PHONY : red/fast

#=============================================================================
# Target rules for targets named blue

# Build rule for target.
blue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blue
.PHONY : blue

# fast build rule for target.
blue/fast:
	$(MAKE) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/build
.PHONY : blue/fast

blue.o: blue.cpp.o

.PHONY : blue.o

# target to build an object file
blue.cpp.o:
	$(MAKE) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue.cpp.o
.PHONY : blue.cpp.o

blue.i: blue.cpp.i

.PHONY : blue.i

# target to preprocess a source file
blue.cpp.i:
	$(MAKE) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue.cpp.i
.PHONY : blue.cpp.i

blue.s: blue.cpp.s

.PHONY : blue.s

# target to generate assembly for a file
blue.cpp.s:
	$(MAKE) -f CMakeFiles/blue.dir/build.make CMakeFiles/blue.dir/blue.cpp.s
.PHONY : blue.cpp.s

red.o: red.cpp.o

.PHONY : red.o

# target to build an object file
red.cpp.o:
	$(MAKE) -f CMakeFiles/red.dir/build.make CMakeFiles/red.dir/red.cpp.o
.PHONY : red.cpp.o

red.i: red.cpp.i

.PHONY : red.i

# target to preprocess a source file
red.cpp.i:
	$(MAKE) -f CMakeFiles/red.dir/build.make CMakeFiles/red.dir/red.cpp.i
.PHONY : red.cpp.i

red.s: red.cpp.s

.PHONY : red.s

# target to generate assembly for a file
red.cpp.s:
	$(MAKE) -f CMakeFiles/red.dir/build.make CMakeFiles/red.dir/red.cpp.s
.PHONY : red.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... red"
	@echo "... blue"
	@echo "... blue.o"
	@echo "... blue.i"
	@echo "... blue.s"
	@echo "... red.o"
	@echo "... red.i"
	@echo "... red.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

